fix = true

[format]
docstring-code-format = true

[lint]
select = [
  "ASYNC", # flake8-async
  "B",     # flake8-bugbear
  "C4",    # flake8-comprehensions
  "FA",    # flake8-future-annotations
  "G",     # flake8-logging-format
  "LOG",   # flake8-logging
  "PIE",   # flake8-pie
  "PTH",   # flake8-use-pathlib
  "SIM",   # flake8-simplify
  "TC",    # flake8-type-checking
  #
  "C90",  # mccabe
  "F",    # Pyflakes
  "FAST", # FastAPI
  "I",    # isort
  "PERF", # Perflint
  "RUF",  # Ruff-specific rule
  "UP",   # pyupgrade
  #
  "E", # pycodestyle
  "W", # pycodestyle
]

[lint.pydocstyle]
convention = "google"
